- README.md
- charts-syncer.yaml
- docs/development.md
- testdata/example-config.yaml
This is just a documentation PR. It adds the following sections to the readme:
- The requirements a chart source fulfill so that the tool can move it to another repository
- Changes performed in the chart code
- Harbor example
- Other improvements
> Improve docs

- .gitignore
This patch just ignores the `.vscode` settings
> fix(gitignore): Ignore vscode settings

- api/config_test.go
This patch moves api tests to a different package.
> fix(api): Refactor api tests

- pkg/chart/sync.go
- pkg/chart/sync_test.go
This patch removes an unused method.
> fix(chart): Remove SyncAllVersions method

- pkg/chart/chart_test.go
- pkg/chart/dependency.go
- pkg/chart/sync.go
- pkg/chart/sync_test.go
- pkg/chartrepotest/chartmuseumfake.go
- pkg/chartrepotest/harborfake.go
- pkg/client/core/chartmuseum.go
- pkg/client/core/chartmuseum_test.go
- pkg/client/core/client.go
- pkg/client/core/client_test.go
- pkg/client/core/common.go
- pkg/client/core/harbor.go
- pkg/client/core/harbor_test.go
- pkg/client/core/helmclassic.go
- pkg/client/core/helmclassic_test.go
- pkg/syncer/syncer.go
This patch is moving code around only.
> fix(pkg): Rename repo package to client/core

- pkg/syncer/syncer.go
- pkg/utils/utils.go
This patch defines the Unix epoch in the utils package.
> feat(utils): Expose unix epoch

- cmd/root.go
- cmd/syncpending.go
- pkg/syncer/index.go
- pkg/syncer/sync.go
This patch adds a hidden command to allow us to develop and test the experimental clients.
> feat(syncer): Add SyncPendingCharts method

- pkg/client/helmclassic/helmclassic.go
- pkg/config/config.go
This patch improves some log messages only.
> fix(misc): Improve some log messages

- README.md
- charts-syncer.yaml
Just some minor updates on the README file after adding OCI support
> docs(readme): Update README after adding OCI support

- examples/chartmuseum.yaml
- internal/cache/cache.go
- internal/cache/storer.go
- internal/utils/utils.go
- pkg/client/chartmuseum/chartmuseum.go
- pkg/client/core/core.go
- pkg/client/fake/fake.go
- pkg/client/harbor/harbor.go
- pkg/client/helmclassic/helmclassic.go
- pkg/client/oci/oci.go
- pkg/client/types/types.go
- pkg/syncer/fakesyncer.go
- pkg/syncer/index.go
- pkg/syncer/sync.go
- pkg/syncer/syncer.go
This patch reworks the syncer cache and moves it to the clients so all of them are efficient by themselves.
> feat: Add cache to clients

- internal/utils/utils.go
This PR just re-implements the Untar function from the utils package to not depends on `tar` system command. Instead it makes used of golang native libraries.
Fixes #45
> feat(tar): remove tar dependency

- pkg/client/helmclassic/helmclassic_test.go
Just move helmclassic tests from `helmclassic` package to `helmclassic_test` package
> test: repackage helmclassic tests

- pkg/client/local/local_test.go
This PR adds unit tests for the local client
> test(local): Added unit tests for local client

- pkg/client/harbor/harbor.go
- pkg/client/harbor/harbor_test.go
- pkg/client/harbor/harbortester.go
This PRs adds unit tests for the harbor client implementation
> feat(harbor): Add unit tests for harbor clients

- README.md
We added a LOCAL kind in the past but forget to document the use case in the README
> docs: document LOCAL kind for chart repos

- internal/utils/utils.go
- internal/utils/utils_test.go
We have been reported at #102 that the current logic does not support providing an index that refers to charts using a different host to the one hosting the index YAML file.
We didn't consider this use case due to a bug in the `NormalizeChartURL` method at the `internal/utils` package. After checking the PR, we noticed that our CI tests were not being triggered and we started looking into the issue.
This patch fixes the bug and other omitted edge cases and we can consider #102 as closed after merging it.
Nevertheless, we would like to appreciate the effort, time, and patience that @marthydavid has dedicated! :)
> fix: Fix how we normalize chart URLs

- pkg/client/intermediate/intermediate_test.go
- pkg/syncer/sync_internal_test.go
Added tests for new intermediate client added at #120 as well as some syncer methods to get the proper relok8s request.
> test: add tests for new functions related to airgap support

- internal/config/config.go
Fixes a regression added [here](https://github.com/bitnami-labs/charts-syncer/pull/134) affecting to authentication in the airgap scenario
Refs https://github.com/bitnami-labs/charts-syncer/issues/118
Signed-off-by: Miguel Martinez Trivino <mtrivino@vmware.com>
> fix: authentication in intermediate scenario

- docs/airgap.md
I updated the sample yamls here to add the auth values that were required to get this working.
> update sample yamls airgap.md

- docs/airgap.md
Minor tweaks in the airgap documentation to be consistent with the other examples we have such as this one https://github.com/bitnami-labs/charts-syncer#configuration
> chore: Minor tweaks in airgap documentation

- go.mod
- go.sum
This PR fixes https://github.com/bitnami-labs/charts-syncer/security/dependabot/2
> misc: Fix security vulnerabilities

- internal/indexer/resolver.go
- internal/utils/utils.go
- pkg/client/repo/chartmuseum/chartmuseum.go
- pkg/client/repo/harbor/harbor.go
- pkg/client/repo/helmclassic/helmclassic.go
- pkg/client/repo/oci/oci.go
This PR adds the option to use a http proxy if set within environment variables
> feat: add proxy from env transport option
