api/config_test.go, cmd/sync.go, cmd/sync_chart.go, pkg/chart/chart_test.go, pkg/chart/dependency.go, pkg/chart/dependency_test.go, pkg/chart/sync_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/repo/chartmuseum.go, pkg/repo/chartmuseum_test.go, pkg/repo/common.go, pkg/repo/harbor.go, pkg/repo/harbor_test.go, pkg/repo/helmclassic.go, pkg/repo/helmclassic_test.go, pkg/utils/utils_test.go
Fix #23 
- errors are now **not** capitalized as recommended for golang projects. https://github.com/golang/go/wiki/CodeReviewComments#error-strings
- use `t.Fatal(f)` instead of `t.Error(f)` if it fails a test preparation step instead of the test itself
=> not capitalize errors and use t.Fatalf if test preparation step fail

README.md, api/api.go, deployment/cronjob.yaml, pkg/config/config.go, pkg/config/config_test.go, testdata/example-config-no-auth.yaml, testdata/example-config-user-file.yaml
Since we stop using viper to unmarshall the config file the method `viper.BindEnv` stop working too and we lost the ability to set auth properties from env vars.
This PR enables the functionality again and adds a test to verify it continues working on future releases.
Fix #31
=> Fix getting auth properties from env vars

cmd/sync_chart.go
Add a new CLI flag (`--sync-deps`) to the `syncChart` command to tell the tool to also synchronize missing dependencies when syncing a single chart.
Fix #32
=> Add sync dependencies flag

cmd/sync.go, cmd/sync_chart.go, pkg/chart/dependency.go, pkg/chart/dependency_test.go, pkg/chart/sync.go, pkg/chart/sync_test.go, pkg/chartrepotest/chartmuseumreal.go, pkg/repo/chartmuseum.go, pkg/repo/chartmuseum_test.go, pkg/repo/client.go, pkg/repo/harbor.go, pkg/repo/harbor_test.go, pkg/repo/helmclassic.go, pkg/repo/helmclassic_test.go, pkg/utils/utils.go, pkg/utils/utils_test.go, testdata/zookeeper-index.yaml
This PR is a small refactor so that the `chartsExists()` function does not download the target index.yaml in each call. We detect this was making the tool to run slowly in certain environments.
Additionally, it fixes an issue with the `FindChartURL()` function when the URL stored in the index.yaml is relative and not absolute.
Fixes #33
=> Avoid download target index.yaml several times

pkg/syncer/syncer.go
This patch adds a `syncer` package to encapsulate the sync logic.
This initial encapsulation is pretty basic. If we plan to add support for other backends, it should be refactored further to decouple the sync logic from the backend implementation while keeping a clean interface.
=> feat(syncer): Add syncer pkg

cmd/sync.go
This patch just fixes a typo showing unnecessary information.
=> fix(cmd): Fix typo

pkg/syncer/syncer.go
This patch adds a `New` method, which will return an enhanced version of `Syncer` containing the new `ClientV2` chart repo clients.
These clients will replace the current ones as we implement pending features.
=> feat(syncer): Enhance syncer struct

pkg/client/chartmuseum/chartmuseum.go, pkg/client/core/core.go, pkg/client/harbor/harbor.go, pkg/client/helmclassic/helmclassic.go, pkg/utils/utils.go
To reload the `index.yaml` file is an expensive task. This patch implements the `Reload` method in the `Client` API so processes will call it on-demand to refresh chart repo clients.
=> feat(client): Add Reload method

pkg/syncer/sync.go, pkg/syncer/syncer.go
This patch splits `syncer.go` in different files to ease future features.
=> fix(syncer): Split code into different files

go.mod, go.sum, pkg/chart/dependency.go, pkg/client/helmclassic/helmclassic.go, pkg/syncer/index.go, pkg/syncer/syncer.go
This patch adds [topological sort](https://en.wikipedia.org/wiki/Topological_sorting) capabilities to the `Syncer`.
This allows the `Syncer` to compute the list of charts to synchronize in a way that eases the subsequent uploads to the target chart repository.
=> feat(syncer): Add topological sort for charts

cmd/syncpending.go, pkg/syncer/index.go, pkg/syncer/syncer.go, pkg/syncer/workdir.go, pkg/utils/utils.go
The current `Syncer` stores charts in a temporary folder. This patch adds a local working directory to prevent downloading the charts over and over in each run.
This is not especially useful for a real case usage of this tool in which we will only download a big number of charts the first time syncing two chart repos. We can consider that subsequent runs will download only a few of them. In any case, subcharts (dependencies) might be the same in these subsequent runs, so it still makes sense to add this feature to improve the performance of the tool in real cases.
The reality is that this is extremely useful to speed up the development process.
Example:
```shell
❯ echo -n https://charts.bitnami.com/bitnami | sha1sum -t
cc54f5167101a3913ef8e9c2aff515129771b204  -
❯ tree ~/.charts-syncer/ …
```
=> feat(syncer): Add SyncPendingCharts method

pkg/client/chartmuseum/chartmuseum.go, pkg/client/harbor/harbor.go, pkg/client/helmclassic/helmclassic.go, pkg/syncer/index.go, pkg/syncer/syncer.go, pkg/utils/utils.go
The current client implementations are only taking 404 HTTP responses into account. However, we might receive other non-2xx errors.
This patch will make clients take into account all non-2xx responses, instead. It also adds an string identifier to each query log.
=> feat(client): Improve HTTP response handling

pkg/chart/chart.go, pkg/chart/dependency.go, pkg/chart/sync.go, pkg/client/chartmuseum/chartmuseum.go, pkg/client/harbor/harbor.go, pkg/client/helmclassic/helmclassic.go, pkg/helmcli/helmcli.go, pkg/syncer/index.go, pkg/syncer/sync.go, pkg/syncer/syncer.go, pkg/utils/utils.go, test/install-ghost.sh
This patch adds the core logic for syncing pending charts.
```shell
❯ ./dist/charts-syncer --config test/test-config.yaml sync-pending --from-date 2020-10-01
I1125 12:21:35.263726   50802 sync.go:32] Using config file: "test/test-config.yaml"
W1125 12:21:35.264320   50802 config.go:29] 'target.repoName' property is empty. Using 'myrepo' default value
I1125 12:21:37.526413   50802 sync.go:107] There are 18 charts out of sync!
I1125 12:21:37.526428   50802 sync.go:118] Syncing "common-0.7.1" chart...
I1125 12:21:37.597341   50802 sync.go:118] Syncing "common-1.0.1" chart...
I1125 12:21:37.684631   50802 sync.go:118] Syncing "mariadb-7.10.3" chart...
I1125 12:21:37.775901   50802 sync.go:118] Syncing "common-0.8.0" chart...
I1125 12:21:37.852975   50802 sync.go:118] Syncing "common-1.0.0" …
```
=> feat(syncer): Add sync pending logic

pkg/client/chartmuseum/chartmuseum.go, pkg/client/core/core.go, pkg/client/harbor/harbor.go, pkg/client/helmclassic/helmclassic.go, pkg/syncer/sync.go
Both #67 and #70 require an extended version of `Upload` that accepts `name` and `version` chart values.
=> feat(client): Extend Upload API to accept name and version fields

.github/workflows/release.yaml, .goreleaser.yml, Dockerfile
This PR includes changes to be able to publish a new version of `charts-syncer` to gcr.io/bitnami-labs on each release.
Changes included:
- Added `dockers` section to `goreleaser.yml` and sets up necessary configuration. It will push two images, one with the `latest` tag and another one with the actual version.
- Updated `Dockerfile` to be able to install additional dependencies needed by `charts-syncer`.
- Updated version of goreleaser to v2.
- Added a new docker-login action to be able to authenticate to gcr.io.
- Added `GCR_JSON_KEY` to GitHub repository's secrets.
=> feat(ci): Set up publishing to bitnami-labs registry

README.md, deployment/cronjob.yaml
This PR contains the following changes:
- adds a table of content to the README
- fix some typos
- update the deploy to kubernetes section as docker images are already published to `gcr.io/bitnami-labs/charts-syncer`
=> misc(readme): add ToC and some typo fixing

pkg/syncer/fakesyncer.go, pkg/syncer/index_internal_test.go, pkg/syncer/sync_test.go
This PR uses the fake (local-impl) client feature to add tests for the `SyncPendingCharts` functionality, which is the core of this tool.
=> feat(syncer): Add SyncPendingCharts tests

internal/utils/utils.go, internal/utils/utils_test.go
This PR just improves a bit the Untar unit tests so we also check that files from subfolders in the tarball are properly uncompressed.
=> test: improve Untar unit tests

pkg/client/helmclassic/helmclassic.go, pkg/client/helmclassic/helmclassic_test.go, pkg/client/helmclassic/helmclassictester.go, testdata/index.yaml
This PR adds unit tests for Helmclassic implementation.
There is duplicated code from #90, so I plan to refactor/rebase those chartmuseum tests after helm one has been merged.
=> test(helmclassic): Add unit tests for helmclassic client

Dockerfile, Makefile
After removing external helm cli and tar dependencies in #84 and #85 we can simply use a scratch container
=> feat: use from scratch in Dockerfile

internal/utils/utils.go, internal/utils/utils_test.go, pkg/client/helmclassic/helmclassic.go, pkg/client/helmclassic/helmclassic_test.go, testdata/index-relative.yaml
While testing a replication from Harbor to Habor I notice this issue. We were returning the URL as it is in the index.yaml, however, this URL can be absolute or relative. 
**absolute**
```
urls:
- https://some.repo.url/charts/nginx-5.1.1.tgz
```
**relative**
```
urls:
- charts/nginx-5.1.1.tgz
```
We were assuming it was an absolute URL, so in the case it is not, we should transform it first:
=> fix(GetDownloadURL): Fix chart download url when url is relative in index.yaml

cmd/root.go, cmd/sync.go, pkg/client/chartmuseum/chartmuseum.go, pkg/client/chartmuseum/chartmuseum_test.go, pkg/client/core/core.go, pkg/client/harbor/harbor.go, pkg/client/harbor/harbor_test.go, pkg/client/helmclassic/helmclassic.go, pkg/client/helmclassic/helmclassic_test.go, pkg/client/oci/oci.go, pkg/client/oci/oci_test.go, pkg/client/types/types.go, pkg/syncer/syncer.go
This PR adds a `--insecure` command-line flag to allow skipping TLS checks for example when using self-signed certificate during development or testing.
Fixes https://github.com/bitnami-labs/charts-syncer/issues/78
=> feat: add insecure flag

internal/chart/chart_test.go, internal/chart/dependency.go, internal/chart/dependency_test.go, pkg/syncer/sync.go
Fixes #81
Fixes #100
I have recovered (and adapted a bit) several functions deleted at https://github.com/bitnami-labs/charts-syncer/pull/76/. In that PR, we removed `helm` dependency, so we stopped using helm cli to build the dependencies and started to do it on our own. Due to that, we stopped modifying dependencies files to point to the new repository url.
=> feat: Update repository URL references in dependencies files

go.mod, go.sum
Fix vulnerability issue reported by GitHub on containerd package.
[Vulnerability link](https://github.com/bitnami-labs/charts-syncer/security/dependabot/go.sum/github.com%2Fcontainerd%2Fcontainerd/open)
=> chore(CVE-2021-41103): update containerd package version

.circleci/config.yml, .github/workflows/release.yaml, .gitignore, .goreleaser.yml, Makefile, cmd/root.go, cmd/version.go, go.mod, go.sum
This PR adds a new `version` command to output the version of the tool.
Additionally it updates the required go version to 1.16
=> feature: add version command

go.mod, go.sum
GitHub Dependabot recommends updating these two packages due to some security issues.
=> chore(package-vulnerability): update containerd and image-spec package version

internal/chart/dependency.go, pkg/client/client.go, pkg/client/intermediate/intermediate.go, pkg/client/repo/core.go, pkg/syncer/syncer.go
Follow up from #120. We can use a more meaningful name for these interfaces
=> refactor: rename reader and writer interfaces

go.mod, go.sum
Update the relok8s dependency to leverage the new multi-leveled, recursive dependency update approach https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/113
This will allow us to sync Helm Charts like `wavefront-adapter-for-istio` which has 3 levels of dependencies 
Tested with the patch and it worked
```
go run main.go sync -c ~/work/bitnami/playground/demo-charts-syncer/config.yaml -v3 --from-date 2021-11-29                        
I1220 13:34:49.011173 3837906 sync.go:33] Using config file: "/home/migmartri/work/bitnami/playground/demo-charts-syncer/config.yaml"                                                                                                                                               
I1220 13:34:49.011573 3837906 syncer.go:114] Using workdir: …
```
=> fix: Update relok8s library to support multi-level dependencies

pkg/syncer/sync.go, pkg/syncer/sync_internal_test.go
Delete the .relocated suffix from chart name so in the target repository is stored as NAME-VERSION.tgz
Fix #125
=> fix: remove .relocated suffix when relok8s is the backend used

go.mod, go.sum
Update the relok8s library to include a fix https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/120 that was altering the sha of the images during an intermediate bundle sync.
Signed-off-by: Miguel Martinez Trivino <mtrivino@vmware.com>
=> chore: bump relok8s version

cmd/sync.go, go.mod, pkg/syncer/index.go, pkg/syncer/sync_test.go, pkg/syncer/syncer.go
This PR adds a new CLI flag --latest-version-only to only sync the latest version of each chart
=> feature: add CLI flag to only sync latest version of charts

go.mod, go.sum
Fix CVE-2021-43816 security issue reported by GitHub dependabot
=> fix: update containerd version to solve CVE-2021-43816

go.mod, go.sum
Updates relok8s library to a version where credentials fallback is disabled https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/138 
Refs  https://github.com/bitnami-labs/charts-syncer/issues/118
=> chore: update relok8s library

.circleci/config.yml
I got an email from circle ci team notifying this ubuntu 16 image will be deprecated on Tuesday, May 31, 2022.
They referred to [this migrating guide](https://circleci.com/docs/2.0/images/linux-vm/16.04-to-20.04-migration/?mkt_tok=NDg1LVpNSC02MjYAAAGCndaKxNgeWk8CnmHaKSOtscOvesy67d8tIpUx6WHhlORxL770li4WtNDf8XUJGjJrdQoIGyxNjGonUHkACYi8X8jtjXuLw53i7HcmhHT8lXY)
=> chore: update circleci machine used for tests

go.mod, go.sum, pkg/syncer/sync.go, pkg/syncer/sync_internal_test.go
Updates the relok8s library to add two new features
- Container registry credentials validation https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/146 
- Remove chart dependency references https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/pull/148
The first one will make chart-syncer fail when the `servername` provided is not valid while the second one will make the relocated Helm Charts to not to have a Chart.lock nor dependencies refs in the Chart.yaml. More info on its rationale here https://github.com/vmware-tanzu/asset-relocation-tool-for-kubernetes/issues/142#issue-1124233145
=> chore: validate OCI registry credentials and fix subchart versions

api/config.go, internal/chart/sync.go
Skip change the value.yaml if not set
```
#
containerRegistry: gcr.io
containerRepository: bitnami-containers
```
reslove : https://github.com/bitnami-labs/charts-syncer/issues/104
=> Skip change the value.yaml 

.circleci/config.yml, test/run-charts-syncer.sh
Update old version of Helm, Kind, and Kubectl used for testing.
Additionally, just sync the latest version of the testing app (ghost) instead of syncing all available versions from specificdate.
=> chore: update testing components version and charts-syncer flags

examples/chartmuseum.yaml, examples/local.yaml, test/run-verifications.sh, test/test-config.yaml
Signed-off-by: Carlos Rodriguez Hernandez <carlosrh@vmware.com>
Replace the deprecated `gcr.io/bitnami-containers` by `docker.io/bitnami`
=> Replace gcr.io/bitnami-containers by docker.io/bitnami

README.md
Signed-off-by: Tomas Pizarro Moreno <tpizarro@vmware.com>
This PR simply documents how to use charts-syncer with ECR repositories due to its peculiarities:
- A temporary password has to be obtained with AWS CLI to operate the ECR registry
- Repositories must exist before pushing any artifact
=> docs: document how to use charts-syncer with Amazon Elastic Container Registry (ECR) repositories

pkg/client/repo/chartmuseum/chartmuseum.go, pkg/client/repo/chartmuseum/chartmuseumtester.go
In fact, The following APIs are all prefixed of chartmuseum
Helm Chart Repository
- `GET /:repo/index.yaml` - retrieved when you run `helm repo add chartmuseum http://localhost:8080/`
- `GET /:repo/charts/mychart-0.1.0.tgz` - retrieved when you run `helm install chartmuseum/mychart`
- `GET /:repo/charts/mychart-0.1.0.tgz.prov` - retrieved when you run `helm install` with the `--verify` flag
Chart Manipulation
- `POST /:repo/api/charts` - upload a new chart version
- `POST /:repo/api/prov` - upload a new provenance file
- `DELETE /:repo/api/charts/<name>/<version>` - delete a chart version (and corresponding provenance file)
- `GET /:repo/api/charts` - list all charts
- `GET /:repo/api/charts/<name>` - list all versions of a chart
- `GET /:repo/api/charts/<name>/<version>` - describe a …
=> Fixed an issue with incorrect use of the chartmuseum API, And update the test cace

pkg/client/repo/oci/oci.go, pkg/client/repo/oci/ocitester.go
For our use case, we want to sync Helm charts between Sonatype Nexus, a classic Helm repo, to Harbor, an OCI registry. This took over three hours to complete, which lead me to investigate what it was doing that was taking so long.
For every version of a chart that it finds on Nexus, it checks if that version already exists on Harbor. To do that, it lists all of that chart’s versions by downloading every single version that exists in Harbor for that chart. For one of our charts, we have 611 versions in Nexus. charts-syncer was doing 611 * 611 = 373.321 GET calls to Harbor. It spent three hours just indexing the charts.
I rewrote the implementation of the Has() method in oci.Repo so that it instead performs a single HEAD request to check if the version is present on the registry. That seems …
=> Rewrite implementation of Has() method in oci.Repo

.circleci/config.yml
The URL where we were downloading `chartmuseum` binary from is no longer valid and executing the "binary" during the tests fails with this error:
```
/usr/local/bin/chartmuseum: line 1: syntax error near unexpected token `newline'
/usr/local/bin/chartmuseum: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
```
I have updated the download instructions with latest info from https://github.com/helm/chartmuseum/releases
=> chore: fix chartmusuem install action

pkg/client/repo/oci/oci.go, pkg/client/repo/oci/oci_test.go
When using ghcr.io as an OCI target then charts-syncer would always overwrite an already existing chart because ghcr.io requires a client to retrieve a bearer token before making any requests against it. This is also true when basic auth credentials are provided. The `Repo#Has` method would always fail in that case because it can't handle 401 responses.
I exchanged the code in the `Has` method to use the go-containerregistry client instead that properly handles authentication.
```
$ go run main.go sync --latest-version-only
I0503 18:44:41.867762 3171500 sync.go:49] Looking for the default config charts-syncer.yaml
I0503 18:44:42.448242 3171500 sync.go:47] There is 1 chart out of sync!
I0503 18:44:42.448269 3171500 sync.go:55] Syncing "grafana-6.56.1" chart...
```
```
$ go run main.go sync …
```
=> Properly discover existing image in OCI target

internal/cache/cachedisk/cachedisk.go, internal/chart/chart.go, internal/chart/chart_test.go, internal/chart/dependency.go, internal/chart/dependency_test.go, internal/config/config.go, internal/indexer/oci.go, internal/utils/utils.go, internal/utils/utils_test.go, pkg/client/repo/chartmuseum/chartmuseum_test.go, pkg/client/repo/core.go, pkg/client/repo/harbor/harbor_test.go, pkg/client/repo/helmclassic/helmclassic.go, pkg/client/repo/helmclassic/helmclassic_test.go, pkg/client/repo/helmclassic/helmclassictester.go, pkg/client/repo/local/local.go, pkg/client/repo/oci/oci.go, pkg/client/repo/oci/ocitester.go, pkg/syncer/fakesyncer.go, pkg/syncer/sync.go, pkg/syncer/sync_test.go
When I was creating the other PR my IDE complained about the ioutil pkg being deprecated.
> Deprecated: As of Go 1.16, the same functionality is now provided by package [io](https://pkg.go.dev/io) or package [os](https://pkg.go.dev/os), and those implementations should be preferred in new code. See the specific function documentation for details.
Looked at the [docs](https://pkg.go.dev/os) and all them simply call an other function from the `os` or `io` pkg. Replicated the deprecated functions with their newer equivalent.
=> fix: replace deprecated iotil functions with os/io equivalents

pkg/client/repo/oci/oci.go, pkg/client/repo/oci/oci_test.go
Closes #182 
Rewrites the OCI`Fetch` function to use the `go-containerregistry` package instead simple a simple GET that was in `FetchAndCache`.
Since the code is OCI specific I moved it into the `oci.go` and left the `FetchAndCache` untouched.
This makes repositories like GHCR.io and Docker Hub work since they require an oauth flow which is now done by the package.
Has the the fix of #186 implemented as well (for the `Fetch` and `ListChartVersions` function, that PR is still relevant for the `Has`). Most of the `go-containerregistry` logic was taken from other functions already using the package.
This isn't yet ready for production I think, I need some feedback/input on:
* error messages and general error management
*  is the logic around `cache.invalidate` still correct? Compared to the …
=> feat: OCI source working with public repositories
